NORFAIR_TRACK:
  DISTANCE_FUNCTION: "frobenius" # mean_manhattan, mean_euclidean, iou, iou_opt
  DISTANCE_THRESHOLD: 500
  HIT_COUNTER_MAX: 15
  INITIALIZATION_DELAY: null
  POINTWISE_HIT_COUNTER_MAX: 4
  DETECTION_THRESHOLD: 0
  PAST_DETECTIONS_LENGTH: 4
  REID_DISTANCE_THRESHOLD: 0
  REID_HIT_COUNTER_MAX: null
